operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
runtimeManifest:
  packages:
    dx-excshell-1:
      license: Apache-2.0
      actions:
        generic:
          function: actions/generic/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: true
            final: true
        getAssets:
          function: actions/getAssets/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
            AEM_AUTHOR: $AEM_AUTHOR
            AEM_STOCK_ENDPOINT: $AEM_STOCK_ENDPOINT
          annotations:
            require-adobe-auth: true
            final: true
        getOffers:
          function: actions/getOffers/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
            AEM_AUTHOR: $AEM_AUTHOR
            AEM_OFFER_ENDPOINT: $AEM_OFFER_ENDPOINT
            AEM_OFFER_PATH: $AEM_OFFER_PATH
          annotations:
            require-adobe-auth: true
            final: true
        createOffer:
          function: actions/createOffer/index.js
          web: 'yes'
          runtime: 'nodejs:14'
          inputs:
            LOG_LEVEL: debug
            AEM_AUTHOR: $AEM_AUTHOR
            AEM_OFFER_ENDPOINT: $AEM_OFFER_ENDPOINT
            AEM_OFFER_PATH: $AEM_OFFER_PATH
          annotations:
            require-adobe-auth: true
            final: true
